include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    unnecessary_library_name: ignore
    use_build_context_synchronously: ignore

linter: 
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_const_constructors: true