name: flex_calendar_plus
description: "A fully customizable Flutter calendar widget with support for single and multiple date
  selection modes, event management, customizable cell builders, headers, and draggable
  bottom sheets for event details"
version: 1.0.0
homepage: https://github.com/mirzamahmud/flex-calendar-plus
repository: https://github.com/mirzamahmud/flex-calendar-plus
issue_tracker: https://github.com/mirzamahmud/flex-calendar-plus/issues
documentation: https://github.com/mirzamahmud/flex-calendar-plus#readme

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: any

flutter:
  uses-material-design: true

# Licensing information
# Make sure you have a LICENSE file in the root of your repo.
license: MIT
