name: flex_calendar_plus
description: "A customizable Flutter calendar widget with single & multiple date selection, event management, custom headers, and draggable event bottom sheets."
version: 1.0.1
homepage: https://github.com/mirzamahmud/flex_calendar_plus
repository: https://github.com/mirzamahmud/flex_calendar_plus
issue_tracker: https://github.com/mirzamahmud/flex_calendar_plus/issues
documentation: https://github.com/mirzamahmud/flex_calendar_plus#readme

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: any

flutter:
  uses-material-design: true

# Licensing information
# Make sure you have a LICENSE file in the root of your repo.
license: MIT
